services:
  - type: web
    name: lms-platform
    runtime: node
    rootDir: .
    plan: free
    buildCommand: npm install && npm run render-build
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
